# Generated by Selenium IDE
import pytest
import time
import json
from selenium.webdriver.firefox.options import Options
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTitleCheck():
  def setup_method(self, method):
    firefox_options = Options()
    firefox_options.add_argument('--headless')  # Run in headless mode
    self.driver = webdriver.Remote(
      command_executor='http://localhost:4444',
      options=firefox_options
    )
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_titleCheck(self):
    self.driver.get("http://frontend:80")
    assert self.driver.find_element(By.CSS_SELECTOR, ".ant-typography:nth-child(2)").text == "NUSHungry"
    elements = self.driver.find_elements(By.CSS_SELECTOR, "div:nth-child(1) > img")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".leaflet-host")
    assert len(elements) > 0
  
