name: Deploy to Amazon ECS

on:
  push:
    branches: ["release"]
  pull_request:
    branches: ["release"]

env:
  AWS_REGION: ap-southeast-1
  ECR_REPOSITORY: nushungry/frontend
  ECS_SERVICE: nushungry-dev-frontend-service
  ECS_CLUSTER: nushungry-dev-cluster
  ECS_TASK_DEFINITION: .aws/task-definition.json
  CONTAINER_NAME: nushungry-dev-frontend

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: "true"

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION }}
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
  performance-tests:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-docker-action@v4
      - name: Performance test
        run: |
          docker run --workdir "/tests" --name test-jmeter -v "./tests/performance":/tests alpine/jmeter:5.6.3 -n -t "NUSHungrySmokeTest.jmx" -l "logs/results.jtl" -e -o "html"
          docker rm -f test-jmeter

      - name: Upload artefacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: performance-test-results
          path: /tests/performance/
          retention-days: 7
