name: E2E Tests

on:
  push:
    branches: ["feat/frontend-ci-pipeline"]
  pull_request:
    branches: ["feat/frontend-ci-pipeline"]
jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Set up E2E test environment
        env:
          AWS_REGION: ap-southeast-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          npm install -g aws-cli
          aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin ${{ secrets.IMAGE_REGISTRY }}
          docker pull ${{ secrets.IMAGE_REGISTRY }}/monolith-backend:latest
          docker compose up
      - name: Get latest Firefox version
        run: |
          echo "FIREFOX_VERSION=$(firefox -v)" >> $GITHUB_ENV
          echo "Firefox version is $FIREFOX_VERSION"
